name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to the branch you want to trigger the deployment from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js (if needed for rendering)
      uses: actions/setup-node@v4
      with:
        node-version: '14'  # Specify the Node.js version you need

    # - name: Render HTML (if needed)
    #   run: |
    #     # Add commands to render your HTML files here
    #     # For example, if you're using a static site generator:
    #     npm install
    #     npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./published